##
## Makefile : for Static/Shared/Dynamic Library Programming
##
##		Kim Soo Hyun(@")
##

PLATFORM = 

INC_PATH = ________
CC = $(PLATFORM)gcc
CFLAGS = ________
LIB_PATH_STATIC = _______

app : app.o
	@echo "app create using static library...."
	___________
	___________

clean :
	___________
	-rm -f app app.o


