##
## Makefile : for Static/Shared/Dynamic Library Programming
##
##		Kim Soo Hyun(@")
##

PLATFORM = 

CC = $(PLATFORM)gcc
CFLAGS = -Wall -O2
ARFLAGS = -rcs


..............
	

clean :
	-rm -f $(LIB_OBJS)
	-rm -f libtest.a


